[project]
name = "base-fastapi-project"
version = "0.1.0"
description = ""
authors = [{ name = "Anton Kholkin", email = "kholkin.anthony@gmail.com" }]
requires-python = ">=3.11,<4"
readme = "../README.md"
dependencies = [
    "fastapi>=0.100.0,<0.101",
    "alembic>=1.11.1,<2",
    "inflection>=0.5.1,<0.6",
    "uvicorn>=0.22.0,<0.23",
    "pydantic>=2.1.1,<3",
    "pydantic-settings>=2.0.2,<3",
    "sqlalchemy[mypy]>=2.0.15,<3",
    "asyncpg>=0.27.0,<0.28",
    "greenlet>=2.0.2,<3",
    "httpx>=0.24.1,<0.25",
    "python-multipart>=0.0.6,<0.0.7",
    "loguru>=0.7.0,<0.8",
    "authlib>=1.2.1,<2",
    "itsdangerous>=2.1.2,<3",
    "pytz>=2024.2,<2025",
    "aioboto3>=13.2.0,<14",
]

[dependency-groups]
dev = [
    "ruff>=0.1.7,<0.2",
    "bump-pydantic>=0.6.1,<0.7",
    "pytest>=8.1.1,<9",
    "pytest-asyncio>=0.21.0,<0.22",
    "pytest-factoryboy>=2.5.1,<3",
    "pytest-mock>=3.14.0,<4",
    "pytest-repeat>=0.9.3,<0.10",
    "types-redis>=4.6.0.0,<5",
    "types-pytz>=2024.1.0.20240417,<2025",
    "types-aiofiles>=24.1.0.20240626,<25",
]

[tool.uv]
package = false

[tool.ruff]
line-length = 120

