[project]
name = "base-fastapi-project"
version = "0.1.0"
description = ""
authors = [{ name = "Anton Kholkin", email = "kholkin.anthony@gmail.com" }]
requires-python = ">=3.14"
readme = "../README.md"
dependencies = [
    "aioboto3>=15.5.0",
    "aiofiles>=25.1.0",
    "alembic>=1.20.0",
    "asyncpg>=0.32.0",
    "authlib>=1.8.0",
    "fastapi>=0.143.0",
    "httpx>=0.28.1",
    "inflection>=0.5.1",
    "itsdangerous>=2.2.0",
    "loguru>=0.7.3",
    "pydantic>=2.14.0",
    "pydantic-settings>=2.15.0",
    "python-multipart>=0.0.32",
    "redis>=8.1.0",
    "sqlalchemy[asyncio]>=2.1.4",
    "uvicorn>=0.54.0",
]

[dependency-groups]
dev = [
    "bump-pydantic>=0.8.0",
    "mypy>=2.4.0",
    "pytest>=9.1.1",
    "pytest-asyncio>=1.4.0",
    "pytest-factoryboy>=2.8.1",
    "pytest-mock>=3.16.0",
    "pytest-repeat>=0.9.4",
    "ruff>=0.16.10",
    "types-aiofiles>=25.1.0.20260518",
]

[tool.uv]
package = false

[tool.ruff]
line-length = 120

[tool.pytest.ini_options]
asyncio_default_fixture_loop_scope = "session"
asyncio_default_test_loop_scope = "session"

